import type { ToolName } from "../tools/names.js";

export const TOOL_LABELS: Record<ToolName, string> = {
    project_list: "列出已注册项目",
    project_select: "绑定项目",
    project_current: "查看当前项目",
    project_unbind: "解绑项目",
    project_control: "管理会话项目",
    read: "读取文件",
    read_many: "批量读取文件",
    write: "写入文件",
    edit: "修改文件",
    apply_patch: "应用补丁",
    bash: "执行命令",
    exec_command: "后台命令",
    write_stdin: "进程交互",
    process_kill: "结束进程",
    process_list: "列出进程",
    process_status: "查看进程",
    process_output: "查看进程输出",
    runtime_status: "查看运行指标",
    server_info: "查看服务信息",
    grep: "搜索内容",
    glob: "查找文件",
    ls: "列出目录",
    webfetch: "抓取网页",
    summary: "总结进度",
    goal_start: "开始长期目标",
    goal_status: "查看长期目标",
    goal_update: "更新长期目标",
    goal_verify: "验证目标条件",
    goal_finish: "完成长期目标",
    goal_cancel: "取消长期目标",
    settings_get: "打开设置",
    settings_update: "更新设置",
    permission_list: "查看外部授权",
    permission_grant: "授权外部访问",
    permission_revoke: "撤销外部授权",
    permission_control: "管理外部授权",
    skills_list: "列出 Codex Skills",
    skill_read: "读取 Codex Skill",
    agents_for_path: "读取项目指令",
    capabilities_reload: "刷新 Codex 能力",
    workspace_roots: "列出工作区",
    workspace_add: "添加工作区",
    workspace_remove: "移除工作区",
    workspace_control: "管理工作区",
    workspace_projects: "列出工作区项目",
    workspace_search: "搜索工作区",
    workspace_context: "读取项目上下文",
    context_pack: "构建任务上下文",
    git_status: "读取 Git 状态",
    git_diff: "读取 Git 差异",
    git_log: "读取 Git 历史",
    git_show: "查看 Git 提交",
    git_branches: "列出 Git 分支",
    code_explore: "探索代码关系",
    mcp_servers: "列出下游 MCP",
    mcp_reconnect: "重连下游 MCP",
    mcp_tools: "列出下游工具",
    mcp_call: "调用下游工具",
    mcp_resources: "列出下游资源",
    mcp_resource_read: "读取下游资源",
    mcp_prompts: "列出下游提示词",
    mcp_prompt_get: "读取下游提示词",
};

export const TOOL_STATUS: Record<ToolName, { invoking: string; invoked: string }> = {
    project_list: { invoking: "正在列出已注册项目…", invoked: "已注册项目已列出" },
    project_select: { invoking: "正在绑定项目…", invoked: "项目绑定完成" },
    project_current: { invoking: "正在查看当前项目…", invoked: "当前项目已读取" },
    project_unbind: { invoking: "正在解绑项目…", invoked: "项目已解绑" },
    project_control: { invoking: "正在管理会话项目…", invoked: "会话项目已更新" },
    read: { invoking: "正在读取文件…", invoked: "文件读取完成" },
    read_many: { invoking: "正在批量读取文件…", invoked: "批量读取完成" },
    write: { invoking: "正在写入文件…", invoked: "文件写入完成" },
    edit: { invoking: "正在修改文件…", invoked: "文件修改完成" },
    apply_patch: { invoking: "正在应用补丁…", invoked: "补丁应用完成" },
    bash: { invoking: "正在执行命令…", invoked: "命令执行完成" },
    exec_command: { invoking: "正在启动后台命令…", invoked: "后台命令已就绪" },
    write_stdin: { invoking: "正在与进程交互…", invoked: "进程交互完成" },
    process_kill: { invoking: "正在结束进程…", invoked: "进程已结束" },
    process_list: { invoking: "正在列出进程…", invoked: "进程列表完成" },
    process_status: { invoking: "正在查看进程…", invoked: "进程状态已读取" },
    process_output: { invoking: "正在查看进程输出…", invoked: "进程输出已读取" },
    runtime_status: { invoking: "正在读取运行指标…", invoked: "运行指标已读取" },
    server_info: { invoking: "正在读取服务信息…", invoked: "服务信息已读取" },
    grep: { invoking: "正在搜索内容…", invoked: "内容搜索完成" },
    glob: { invoking: "正在查找文件…", invoked: "文件查找完成" },
    ls: { invoking: "正在列出目录…", invoked: "目录列表完成" },
    webfetch: { invoking: "正在抓取网页…", invoked: "网页抓取完成" },
    summary: { invoking: "正在总结进度…", invoked: "进度已汇报" },
    goal_start: { invoking: "正在建立长期目标…", invoked: "长期目标已建立" },
    goal_status: { invoking: "正在读取长期目标…", invoked: "长期目标已读取" },
    goal_update: { invoking: "正在更新长期目标…", invoked: "长期目标已更新" },
    goal_verify: { invoking: "正在记录验证结果…", invoked: "验证结果已记录" },
    goal_finish: { invoking: "正在完成长期目标…", invoked: "长期目标已完成" },
    goal_cancel: { invoking: "正在取消长期目标…", invoked: "长期目标已取消" },
    settings_get: { invoking: "正在打开设置…", invoked: "设置已打开" },
    settings_update: { invoking: "正在保存设置…", invoked: "设置已保存" },
    permission_list: { invoking: "正在查看外部授权…", invoked: "外部授权已列出" },
    permission_grant: { invoking: "正在授权外部访问…", invoked: "外部访问已授权" },
    permission_revoke: { invoking: "正在撤销外部授权…", invoked: "外部授权已撤销" },
    permission_control: { invoking: "正在管理外部授权…", invoked: "外部授权已更新" },
    skills_list: { invoking: "正在列出 Codex Skills…", invoked: "Codex Skills 已列出" },
    skill_read: { invoking: "正在读取 Codex Skill…", invoked: "Codex Skill 已读取" },
    agents_for_path: { invoking: "正在读取项目指令…", invoked: "项目指令已加载" },
    capabilities_reload: { invoking: "正在刷新 Codex 能力…", invoked: "Codex 能力已刷新" },
    workspace_roots: { invoking: "正在列出工作区…", invoked: "工作区已列出" },
    workspace_add: { invoking: "正在添加工作区…", invoked: "工作区已添加" },
    workspace_remove: { invoking: "正在移除工作区…", invoked: "工作区已移除" },
    workspace_control: { invoking: "正在管理工作区…", invoked: "工作区已更新" },
    workspace_projects: { invoking: "正在发现工作区项目…", invoked: "工作区项目已列出" },
    workspace_search: { invoking: "正在搜索工作区…", invoked: "工作区搜索完成" },
    workspace_context: { invoking: "正在读取项目上下文…", invoked: "项目上下文已读取" },
    context_pack: { invoking: "正在构建任务上下文…", invoked: "任务上下文已构建" },
    git_status: { invoking: "正在读取 Git 状态…", invoked: "Git 状态已读取" },
    git_diff: { invoking: "正在读取 Git 差异…", invoked: "Git 差异已读取" },
    git_log: { invoking: "正在读取 Git 历史…", invoked: "Git 历史已读取" },
    git_show: { invoking: "正在查看 Git 提交…", invoked: "Git 提交已读取" },
    git_branches: { invoking: "正在列出 Git 分支…", invoked: "Git 分支已列出" },
    code_explore: { invoking: "正在探索代码关系…", invoked: "代码探索完成" },
    mcp_servers: { invoking: "正在读取下游 MCP 状态…", invoked: "下游 MCP 状态已读取" },
    mcp_reconnect: { invoking: "正在重连下游 MCP…", invoked: "下游 MCP 重连完成" },
    mcp_tools: { invoking: "正在列出下游工具…", invoked: "下游工具已列出" },
    mcp_call: { invoking: "正在调用下游工具…", invoked: "下游工具调用完成" },
    mcp_resources: { invoking: "正在列出下游资源…", invoked: "下游资源已列出" },
    mcp_resource_read: { invoking: "正在读取下游资源…", invoked: "下游资源读取完成" },
    mcp_prompts: { invoking: "正在列出下游提示词…", invoked: "下游提示词已列出" },
    mcp_prompt_get: { invoking: "正在读取下游提示词…", invoked: "下游提示词读取完成" },
};

export function toolLabel(toolName: string): string {
    if (Object.prototype.hasOwnProperty.call(TOOL_LABELS, toolName)) {
        return TOOL_LABELS[toolName as ToolName];
    }
    return toolName;
}

export function toolStatus(toolName: string): { invoking: string; invoked: string } {
    if (Object.prototype.hasOwnProperty.call(TOOL_STATUS, toolName)) {
        return TOOL_STATUS[toolName as ToolName];
    }
    return { invoking: "工具调用中…", invoked: "调用完成" };
}
